[program:laravel-worker-api.sedyes.com-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.sedyes.com/artisan queue:work rabbitmq --queue=api.sedyes.com:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.sedyes.com/worker.log
stopwaitsecs=3600

[program:laravel-api.sedyes.com-refund]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.sedyes.com/artisan queue:work rabbitmq --queue=api.sedyes.com:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.sedyes.com/worker-shopify-refund.log
stopwaitsecs=3600


[program:laravel-worker-api.sedyes.com-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.sedyes.com/artisan queue:work rabbitmq --queue=api.sedyes.com:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.sedyes.com/worker.log
stopwaitsecs=3600
