# [program:laravel-worker-api.hautotool.de-order]
# process_name=%(program_name)s_%(process_num)02d
# command=php /www/wwwroot/api.hautotool.de/artisan queue:work rabbitmq --queue=api.hautotool.de:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.hautotool.de/worker.log
# stopwaitsecs=3600

# [program:laravel-api.hautotool.de-refund]
# process_name=%(program_name)s_%(process_num)02d
# command=php /www/wwwroot/api.hautotool.de/artisan queue:work rabbitmq --queue=api.hautotool.de:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.hautotool.de/worker-shopify-refund.log
# stopwaitsecs=3600



