# [program:laravel-worker-api.kundies.cz-order]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.cz/artisan queue:work rabbitmq --queue=api.kundies.cz:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.kundies.cz/worker.log
# stopwaitsecs=3600

# [program:laravel-api.kundies.cz-refund]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.cz/artisan queue:work rabbitmq --queue=api.kundies.cz:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.kundies.cz/worker-shopify-refund.log
# stopwaitsecs=3600



