[program:laravel-worker-api.othshoe.pl-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.pl/artisan queue:work rabbitmq --queue=api.othshoe.pl:orders --sleep=5 --tries=3 --max-time=3600 --memory=256 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.othshoe.pl/worker.log
stopwaitsecs=3600

[program:laravel-api.othshoe.pl-refund]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.pl/artisan queue:work rabbitmq --queue=api.othshoe.pl:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=256 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.othshoe.pl/worker-shopify-refund.log
stopwaitsecs=3600



