[program:laravel-worker-api.wmbh.net-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.wmbh.net/artisan queue:work rabbitmq --queue=api.wmbh.net:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wmbh.net/worker.log
stopwaitsecs=3600

[program:laravel-api.wmbh.net-refund]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.wmbh.net/artisan queue:work rabbitmq --queue=api.wmbh.net:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wmbh.net/worker-shopify-refund.log
stopwaitsecs=3600



