[program:laravel-worker-api.kundies.pl-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.pl/artisan queue:work rabbitmq --queue=api.kundies.pl:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.kundies.pl/worker.log
stopwaitsecs=3600

[program:laravel-api.kundies.pl-refund]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.pl/artisan queue:work rabbitmq --queue=api.kundies.pl:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.kundies.pl/worker-shopify-refund.log
stopwaitsecs=3600


[program:laravel-worker-api.kundies.pl-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.pl/artisan queue:work rabbitmq --queue=api.kundies.pl:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.kundies.pl/worker.log
stopwaitsecs=3600
