# [program:api.othshoe.com-laravel-worker-shopify-orders]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.com/artisan queue:work rabbitmq --queue=api.othshoe.com:orders --sleep=12 --tries=3 --max-time=3600
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.othshoe.com/worker.log
# stopwaitsecs=3600


# [program:api.othshoe.com-laravel-worker-shopify-order-refund]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.com/artisan queue:work rabbitmq --queue=api.othshoe.com:shopify-refund --sleep=60 --tries=10 --timeout=3600
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/api.othshoe.com/worker-shopify-refund.log
# stopwaitsecs=3600



[program:api.othshoe.com-laravel-worker-odoo-orders]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.com/artisan queue:work rabbitmq --queue=api.othshoe.com:odoo_order --sleep=12 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.othshoe.com/worker.log
stopwaitsecs=3600
