[program:laravel-worker-api.wmbra.uk-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/api.wmbra.uk/artisan queue:work rabbitmq --queue=api.wmbra.uk:orders --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wmbra.uk/worker.log
stopwaitsecs=3600

[program:laravel-api.wmbra.uk-refund]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/api.wmbra.uk/artisan queue:work rabbitmq --queue=api.wmbra.uk:shopify-refund --sleep=30 --tries=10 --timeout=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wmbra.uk/worker-shopify-refund.log
stopwaitsecs=3600



