  [program:at-v5.hatme.de]
  directory=/www/wwwroot/at-v5.hatme.de
  command=node /www/wwwroot/at-v5.hatme.de/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/at-v5.hatme.de/at-v5.hatme.de.err.log
  environment=PORT="5014",HOST="0.0.0.0"

