  [program:at.hatme.de]
  directory=/www/wwwroot/at.hatme.de
  command=node /www/wwwroot/at.hatme.de/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/at.hatme.de/at.hatme.de.err.log
  environment=PORT="4005",HOST="0.0.0.0"

