[program:laravel-worker-hatmeo-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/bagisto_project/artisan queue:work rabbitmq --queue=hatmeo:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/bagisto_project/worker.log
stopwaitsecs=3600
