[program:laravel-worker-hameo_de-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/Bagisto/artisan queue:work rabbitmq --queue=hameo_de:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/Bagisto/worker.log
stopwaitsecs=3600

[program:laravel-worker-yooje.uk-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/Bagisto_en/artisan queue:work rabbitmq --queue=yooje_uk:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/Bagisto_en/worker.log
stopwaitsecs=3600

[program:laravel-worker-ro.tdtopic.com-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/ro.tdtopic.com/artisan queue:work rabbitmq --queue=ro_tdtopic_com:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/ro.tdtopic.com/worker.log
stopwaitsecs=3600


[program:laravel-worker-api.wmcer.com-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/Bagisto_es/artisan queue:work rabbitmq --queue=api.wmcer.com:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/Bagisto_es/worker.log
stopwaitsecs=3600
