  [program:cz-v5.mqqhot.com]
  directory=/www/wwwroot/cz-v5.mqqhot.com
  command=node /www/wwwroot/cz-v5.mqqhot.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/cz-v5.mqqhot.com/cz-v5.mqqhot.com.err.log
  environment=PORT="3000",HOST="0.0.0.0"
