[program:cznew.mqqhot.com]
directory=/www/wwwroot/cznew.mqqhot.com
command=node /www/wwwroot/cznew.mqqhot.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/cznew.mqqhot.com/cznew.mqqhot.com.err.log
environment=PORT="4004",HOST="0.0.0.0"
