[program:de.hatme.de]
directory=/www/wwwroot/de.Hatme.de
command=node /www/wwwroot/de.Hatme.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/de.Hatme.de/de.Hatme.de.err.log
environment=PORT="3019",HOST="0.0.0.0"
