[program:de.wmbra.de]
directory=/www/wwwroot/de.Wmbra.de
command=node /www/wwwroot/de.Wmbra.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/de.Wmbra.de/de.Wmbra.de.err.log
environment=PORT="3098",HOST="0.0.0.0"
