  [program:es-cod.wmcer.com]
  directory=/www/wwwroot/es-cod.wmcer.com
  command=node /www/wwwroot/es-cod.wmcer.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/es-cod.wmcer.com/es-cod.wmcer.com.err.log
  environment=PORT="4007",HOST="0.0.0.0"

