[program:es.wmcer.com]
directory=/www/wwwroot/es.wmcer.com
command=node /www/wwwroot/es.wmcer.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/es.wmcer.com/es.wmcer.com.err.log
environment=PORT="3024",HOST="0.0.0.0"
