[program:fr.botma.fr]
directory=/www/wwwroot/fr.botma.fr
command=node /www/wwwroot/fr.botma.fr/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/fr.botma.fr/fr.botma.fr.err.log
environment=PORT="3026",HOST="0.0.0.0"
