[program:gofrei.de]
directory=/www/wwwroot/gofrei.de
command=node /www/wwwroot/gofrei.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/gofrei.de/gofrei.de.err.log
environment=PORT="3028",HOST="0.0.0.0"
