  [program:hu-n5.hatme.net]
  directory=/www/wwwroot/hu-n5.hatme.net
  command=node /www/wwwroot/hu-n5.hatme.net/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/hu-n5.hatme.net/hu-n5.hatme.net.err.log
  environment=PORT="5059",HOST="0.0.0.0"

