  [program:hu-v5.hatme.net]
  directory=/www/wwwroot/hu-v5.hatme.net
  command=node /www/wwwroot/hu-v5.hatme.net/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/hu-v5.hatme.net/hu-v5.hatme.net.err.log
  environment=PORT="3003",HOST="0.0.0.0"
