  [program:it-v5.wmcer.com]
  directory=/www/wwwroot/it-v5.wmcer.com
  command=node /www/wwwroot/it-v5.wmcer.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/it-v5.wmcer.com/it-v5.wmcer.com.err.log
  environment=PORT="5016",HOST="0.0.0.0"

