  [program:it.wmcer.com]
  directory=/www/wwwroot/it.wmcer.com
  command=node /www/wwwroot/it.wmcer.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/it.wmcer.com/it.wmcer.com.err.log
  environment=PORT="4006",HOST="0.0.0.0"

