[program:laravel-worker-api.hatmeo.com-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hatmeo.com/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hatmeo.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.hatmeo.net-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hatmeo.net/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hatmeo.net/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.hautotool.com-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hautotool.com/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hautotool.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.kundies.com-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.com/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.kundies.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.othshoe.com-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.com/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.othshoe.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.wngift.com-erp-shipping]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.wngift.com/artisan erp:shipping_order:sync
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wngift.com/worker.log
stopwaitsecs=3600


