# [program:laravel-worker-shopify-orders]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/bagisto_project/artisan queue:work redis --queue=commands --sleep=10 --tries=3 --max-time=3600 --memory=512
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/bagisto_project/worker.log
# stopwaitsecs=3600

[program:laravel-worker-shopify-product]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/bagisto_project/artisan queue:work redis --queue=shopify-products --sleep=20 --tries=5 --timeout=7200 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/bagisto_project/worker-shopify-products.log
stopwaitsecs=3600

# [program:laravel-worker-shopify-order-refund]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/bagisto_project/artisan queue:work redis --queue=shopify-refund --sleep=60 --tries=10 --timeout=3600 --memory=512
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/bagisto_project/worker-shopify-refund.log
# stopwaitsecs=3600

[program:laravel-worker-shopify-comments]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/bagisto_project/artisan queue:work redis --queue=shopify-comments --sleep=20 --tries=3 --timeout=7200 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/bagisto_project/worker-shopify-comments.log
stopwaitsecs=3600

# [program:laravel-worker-shopify-fulfillments]
# process_name=%(program_name)s_%(process_num)02d
# command=/www/server/php/81/bin/php /www/wwwroot/bagisto_project/artisan queue:work redis --queue=shopify-fulfillments --sleep=600 --tries=3 --timeout=3600 --memory=512
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/www/wwwroot/bagisto_project/worker-shopify-fulfillments.log
# stopwaitsecs=3600
