[program:laravel-worker-api.hatmeo.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hatmeo.com/artisan queue:work rabbitmq --queue=api.hatmeo.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hatmeo.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.hatmeo.net-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hatmeo.net/artisan queue:work rabbitmq --queue=api.hatmeo.net:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hatmeo.net/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.hautotool.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.hautotool.com/artisan queue:work rabbitmq --queue=api.hautotool.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.hautotool.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.kundies.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.kundies.com/artisan queue:work rabbitmq --queue=api.kundies.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.kundies.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.othshoe.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.othshoe.com/artisan queue:work rabbitmq --queue=api.othshoe.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.othshoe.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.wngift.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.wngift.com/artisan queue:work rabbitmq --queue=api.wngift.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wngift.com/worker.log
stopwaitsecs=3600

[program:laravel-worker-api.wngift.com-klaviyo]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/api.wngift.com/artisan queue:work rabbitmq --queue=api.wngift.com:klaviyo_profiles --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/api.wngift.com/worker.log
stopwaitsecs=3600

