  [program:offer-n5.wmcer.com]
  directory=/www/wwwroot/offer-n5.wmcer.com
  command=node /www/wwwroot/offer-n5.wmcer.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-n5.wmcer.com/offer-n5.wmcer.com.err.log
  environment=PORT="5019",HOST="0.0.0.0"

