[program:offer-v5.othshoe.cz]
directory=/www/wwwroot/offer-v5.othshoe.cz
command=node /www/wwwroot/offer-v5.othshoe.cz/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.othshoe.cz/offer-v5.othshoe.cz.err.log
environment=PORT="5054",HOST="0.0.0.0"
