  [program:offer-v5.mqqhot.com]
  directory=/www/wwwroot/offer-v5.mqqhot.com
  command=node /www/wwwroot/offer-v5.mqqhot.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-v5.mqqhot.com/offer-v5.mqqhot.com.err.log
  environment=PORT="5056",HOST="0.0.0.0"

