[program:offer-v5.wmet.net]
directory=/www/wwwroot/offer-v5.wmet.net
command=node /www/wwwroot/offer-v5.wmet.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.wmet.net/offer-v5.wmet.net.err.log
environment=PORT="5005",HOST="0.0.0.0"
