  [program:offer-v5.tdtopic.com]
  directory=/www/wwwroot/offer-v5.tdtopic.com
  command=node /www/wwwroot/offer-v5.tdtopic.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-v5.tdtopic.com/offer-v5.tdtopic.com.err.log
  environment=PORT="5057",HOST="0.0.0.0"

