  [program:offer-n5.hatme.de]
  directory=/www/wwwroot/offer-n5.hatme.de
  command=node /www/wwwroot/offer-n5.hatme.de/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-n5.hatme.de/offer-n5.hatme.de.err.log
  environment=PORT="5017",HOST="0.0.0.0"

