[program:offer-v5.othshoe.pl]
directory=/www/wwwroot/offer-v5.othshoe.pl
command=node /www/wwwroot/offer-v5.othshoe.pl/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.othshoe.pl/offer-v5.othshoe.pl.err.log
environment=PORT="5053",HOST="0.0.0.0"
