  [program:offer-v5.wngift.de]
  directory=/www/wwwroot/offer-v5.wngift.de
  command=node /www/wwwroot/offer-v5.wngift.de/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-v5.wngift.de/offer-v5.wngift.de.err.log
  environment=PORT="5012",HOST="0.0.0.0"

