[program:offer-v5.Wmbra.de]
directory=/www/wwwroot/offer-v5.Wmbra.de
command=node /www/wwwroot/offer-v5.Wmbra.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.Wmbra.de/offer-v5.Wmbra.de.err.log
environment=PORT="5000",HOST="0.0.0.0"
