  [program:offer-v5.sedyes.com]
  directory=/www/wwwroot/offer-v5.sedyes.com
  command=node /www/wwwroot/offer-v5.sedyes.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-v5.sedyes.com/offer-v5.sedyes.com.err.log
  environment=PORT="5055",HOST="0.0.0.0"

