  [program:offer-n5.botma.fr]
  directory=/www/wwwroot/offer-n5.botma.fr
  command=node /www/wwwroot/offer-n5.botma.fr/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-n5.botma.fr/offer-n5.botma.fr.err.log
  environment=PORT="5020",HOST="0.0.0.0"

