[program:offer-v5.kundies.de]
directory=/www/wwwroot/offer-v5.kundies.de
command=node /www/wwwroot/offer-v5.kundies.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.kundies.de/offer-v5.kundies.de.err.log
environment=PORT="3051",HOST="0.0.0.0"
