  [program:offer-v5.wmbh.net]
  directory=/www/wwwroot/offer-v5.wmbh.net
  command=node /www/wwwroot/offer-v5.wmbh.net/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/offer-v5.wmbh.net/offer-v5.wmbh.net.err.log
  environment=PORT="5058",HOST="0.0.0.0"

