[program:offer-v5.othshoe.de]
directory=/www/wwwroot/offer-v5.othshoe.de
command=node /www/wwwroot/offer-v5.othshoe.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/offer-v5.othshoe.de/offer-v5.othshoe.de.err.log
environment=PORT="5007",HOST="0.0.0.0"
