  [program:pl-v5.sedyes.com]
  directory=/www/wwwroot/pl-v5.sedyes.com
  command=node /www/wwwroot/pl-v5.sedyes.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/pl-v5.sedyes.com/pl-v5.sedyes.com.err.log
  environment=PORT="3002",HOST="0.0.0.0"
