[program:laravel-worker-pl.sedyes.com-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/pl.sedyes.com/artisan queue:work rabbitmq --queue=pl_sedyes_com:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/pl.sedyes.com/worker.log
stopwaitsecs=3600
