[program:plnew.sedyes.com]
directory=/www/wwwroot/plnew.sedyes.com
command=node /www/wwwroot/plnew.sedyes.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/plnew.sedyes.com/plnew.sedyes.com.err.log
environment=PORT="4002",HOST="0.0.0.0"
