[program:ro.tdtopic.com]
directory=/www/wwwroot/ro.tdtopic.com
command=node /www/wwwroot/ro.tdtopic.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/ro.tdtopic.com/ro.tdtopic.com.err.log
environment=PORT="4000",HOST="0.0.0.0"
