[program:shop-v5.hatmeo.net]
directory=/www/wwwroot/shop-v5.hatmeo.net
command=node /www/wwwroot/shop-v5.hatmeo.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/shop-v5.hatmeo.net/shop-v5.hatmeo.net.err.log
environment=PORT="5004",HOST="0.0.0.0"
