[program:shop-v5.hatme.de]
directory=/www/wwwroot/shop-v5.hatme.de
command=node /www/wwwroot/shop-v5.hatme.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/shop-v5.hatme.de/shop-v5.hatme.de.err.log
environment=PORT="3002",HOST="0.0.0.0"
