[program:shop-v5.wmcer.com]
directory=/www/wwwroot/shop-v5.wmcer.com
command=node /www/wwwroot/shop-v5.wmcer.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/shop-v5.wmcer.com/shop-v5.wmcer.com.err.log
environment=PORT="3004",HOST="0.0.0.0"
