[program:shop-v5.wmbh.uk]
directory=/www/wwwroot/shop-v5.wmbh.uk
command=node /www/wwwroot/shop-v5.wmbh.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/shop-v5.wmbh.uk/shop-v5.wmbh.uk.err.log
environment=PORT="5003",HOST="0.0.0.0"
