  [program:shop-n5.hatmeo.com]
  directory=/www/wwwroot/shop-n5.hatmeo.com
  command=node /www/wwwroot/shop-n5.hatmeo.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/shop-n5.hatmeo.com/shop-n5.hatmeo.com.err.log
  environment=PORT="5015",HOST="0.0.0.0"

