[program:shop-v5.othshoe.uk]
directory=/www/wwwroot/shop-v5.othshoe.uk
command=node /www/wwwroot/shop-v5.othshoe.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/shop-v5.othshoe.uk/shop-v5.othshoe.uk.err.log
environment=PORT="5008",HOST="0.0.0.0"
