  [program:shop-v5.wngift.com]
  directory=/www/wwwroot/shop-v5.wngift.com
  command=node /www/wwwroot/shop-v5.wngift.com/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/shop-v5.wngift.com/shop-v5.wngift.com.err.log
  environment=PORT="5010",HOST="0.0.0.0"

