  [program:sk-v5.wmbh.net]
  directory=/www/wwwroot/sk-v5.wmbh.net
  command=node /www/wwwroot/sk-v5.wmbh.net/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/sk-v5.wmbh.net/sk-v5.wmbh.net.err.log
  environment=PORT="3001",HOST="0.0.0.0"
