[program:laravel-worker-sk.wmbh.net-odoo-order]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/81/bin/php /www/wwwroot/sk.wmbh.net/artisan queue:work rabbitmq --queue=sk_wmbh_net:odoo_order --sleep=10 --tries=3 --max-time=3600 --memory=128 --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/sk.wmbh.net/worker.log
stopwaitsecs=3600
