[program:slfk.wmbh.net]
directory=/www/wwwroot/slfk.wmbh.net
command=node /www/wwwroot/slfk.wmbh.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/slfk.wmbh.net/slfk.wmbh.net.err.log
environment=PORT="4003",HOST="0.0.0.0"
