[program:test.kundies.com]
directory=/www/wwwroot/test.kundies.com
command=node /www/wwwroot/test.kundies.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/test.kundies.com/test.kundies.com.err.log
environment=PORT="3008",HOST="0.0.0.0"
