[program:uk.wmbra.uk]
directory=/www/wwwroot/uk.wmbra.uk
command=node /www/wwwroot/uk.wmbra.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/uk.wmbra.uk/uk.wmbra.uk.err.log
environment=PORT="3021",HOST="0.0.0.0"
