[program:uk.Wmbrashop.com]
directory=/www/wwwroot/uk.Wmbrashop.com
command=node /www/wwwroot/uk.Wmbrashop.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/uk.Wmbrashop.com/uk.Wmbrashop.com.err.log
environment=PORT="3020",HOST="0.0.0.0"
