[program:uk.yooje.uk]
directory=/www/wwwroot/uk.yooje.uk
command=node /www/wwwroot/uk.yooje.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/uk.yooje.uk/uk.yooje.uk.err.log
environment=PORT="3023",HOST="0.0.0.0"
