[program:us.hatmeo.com]
directory=/www/wwwroot/us.hatmeo.com
command=node /www/wwwroot/us.hatmeo.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/us.hatmeo.com/us.hatmeo.com.err.log
environment=PORT="3017",HOST="0.0.0.0"
