[program:v5.hatmeo.com]
directory=/www/wwwroot/v5.hatmeo.com
command=node /www/wwwroot/v5.hatmeo.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/v5.hatmeo.com/v5.hatmeo.com.err.log
environment=PORT="3000",HOST="0.0.0.0"
