[program:www.othshoe.cz]
directory=/www/wwwroot/www.othshoe.cz
command=node /www/wwwroot/www.othshoe.cz/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.othshoe.cz/www.othshoe.cz.err.log
environment=PORT="3019",HOST="0.0.0.0"
