[program:www.kundies.cz]
directory=/www/wwwroot/www.kundies.cz
command=node /www/wwwroot/www.kundies.cz/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.kundies.cz/www.kundies.cz.err.log
environment=PORT="3015",HOST="0.0.0.0"
