[program:www.othshoe.com]
directory=/www/wwwroot/www.othshoe.com
command=node /www/wwwroot/www.othshoe.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.othshoe.com/www.othshoe.com.err.log
environment=PORT="3010",HOST="0.0.0.0"

