[program:www.wngift.com]
directory=/www/wwwroot/www.wngift.com
command=node /www/wwwroot/www.wngift.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.wngift.com/www.wngift.com.err.log
environment=PORT="3012",HOST="0.0.0.0"
