[program:www.othshoe.uk]
directory=/www/wwwroot/www.othshoe.uk
command=node /www/wwwroot/www.othshoe.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.othshoe.uk/www.othshoe.uk.err.log
environment=PORT="3017",HOST="0.0.0.0"
