[program:www.hautotool.com]
directory=/www/wwwroot/www.hautotool.com
command=node /www/wwwroot/www.hautotool.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.hautotool.com/www.hautotool.com.err.log
environment=PORT="3011",HOST="0.0.0.0"
