[program:www.wmet.net]
directory=/www/wwwroot/www.wmet.net
command=node /www/wwwroot/www.wmet.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.wmet.net/www.wmet.net.err.log
environment=PORT="3016",HOST="0.0.0.0"
