[program:www.othshoe.de]
directory=/www/wwwroot/www.othshoe.de
command=node /www/wwwroot/www.othshoe.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.othshoe.de/www.othshoe.de.err.log
environment=PORT="3016",HOST="0.0.0.0"

