[program:www.wmbh.uk]
directory=/www/wwwroot/www.wmbh.uk
command=node /www/wwwroot/www.wmbh.uk/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.wmbh.uk/www.wmbh.uk.err.log
environment=PORT="3022",HOST="0.0.0.0"
