[program:www.hatmeo.net]
directory=/www/wwwroot/www.hatmeo.net
command=node /www/wwwroot/www.hatmeo.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.hatmeo.net/www.hatmeo.net.err.log
environment=PORT="3025",HOST="0.0.0.0"
