[program:www.kundies.de]
directory=/www/wwwroot/www.kundies.de
command=node /www/wwwroot/www.kundies.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.kundies.de/www.kundies.de.err.log
environment=PORT="3013",HOST="0.0.0.0"
