  [program:www.kundies.pl]
  directory=/www/wwwroot/www.kundies.pl
  command=node /www/wwwroot/www.kundies.pl/.output/server/index.mjs
  autostart=true
  autorestart=true
  stderr_logfile=/www/wwwroot/www.kundies.pl/www.kundies.pl.err.log
  environment=PORT="3014",HOST="0.0.0.0"
