[program:www.wngift.de]
directory=/www/wwwroot/www.wngift.de
command=node /www/wwwroot/www.wngift.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.wngift.de/www.wngift.de.err.log
environment=PORT="3031",HOST="0.0.0.0"
