[program:www.othshoe.pl]
directory=/www/wwwroot/www.othshoe.pl
command=node /www/wwwroot/www.othshoe.pl/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.othshoe.pl/www.othshoe.pl.err.log
environment=PORT="3018",HOST="0.0.0.0"
