[program:www.hautotool.de]
directory=/www/wwwroot/www.hautotool.de
command=node /www/wwwroot/www.hautotool.de/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.hautotool.de/www.hautotool.de.err.log
environment=PORT="3030",HOST="0.0.0.0"
