[program:www.kundies.com]
directory=/www/wwwroot/www.kundies.com
command=node /www/wwwroot/www.kundies.com/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/www.kundies.com/www.kundies.com.err.log
environment=PORT="3009",HOST="0.0.0.0"
