[program:xyl.hatme.net]
directory=/www/wwwroot/xyl.hatme.net
command=node /www/wwwroot/xyl.hatme.net/.output/server/index.mjs
autostart=true
autorestart=true
stderr_logfile=/www/wwwroot/xyl.hatme.net/xyl.hatme.net.err.log
environment=PORT="4001",HOST="0.0.0.0"
